services:
  - type: web
    name: nakayosi-tube-plus
    env: python
    plan: free
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 2
    autoDeploy: true
